#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuFirewallIpsetAVInner' {
    Context 'PVENodesQemuFirewallIpsetAVInner' {
        It 'Initialize-PVENodesQemuFirewallIpsetAVInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuFirewallIpsetAVInner -Comment "TEST_VALUE" -Nomatch "TEST_VALUE" -Digest "TEST_VALUE" -Cidr "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuFirewallIpsetAVInner
            #$NewObject.property | Should -Be 0
        }
    }
}
