#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesDisksLvm' {
    Context 'PVENodesDisksLvm' {
        It 'Initialize-PVENodesDisksLvm' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesDisksLvm -Leaf "TEST_VALUE" -Children "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesDisksLvm
            #$NewObject.property | Should -Be 0
        }
    }
}
