#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesCertificatesInfoInner' {
    Context 'PVENodesCertificatesInfoInner' {
        It 'Initialize-PVENodesCertificatesInfoInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesCertificatesInfoInner -Fingerprint "TEST_VALUE" -Pem "TEST_VALUE" -San "TEST_VALUE" -PublicKeyType "TEST_VALUE" -Notafter "TEST_VALUE" -Filename "TEST_VALUE" -PublicKeyBits "TEST_VALUE" -Notbefore "TEST_VALUE" -Subject "TEST_VALUE" -Issuer "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesCertificatesInfoInner
            #$NewObject.property | Should -Be 0
        }
    }
}
