#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesLxcStatusCurrent' {
    Context 'PVENodesLxcStatusCurrent' {
        It 'Initialize-PVENodesLxcStatusCurrent' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesLxcStatusCurrent -Maxdisk "TEST_VALUE" -Diskread "TEST_VALUE" -Ha "TEST_VALUE" -Netout "TEST_VALUE" -Cpus "TEST_VALUE" -Vmid "TEST_VALUE" -Maxmem "TEST_VALUE" -Tags "TEST_VALUE" -Status "TEST_VALUE" -Lock "TEST_VALUE" -Name "TEST_VALUE" -Template "TEST_VALUE" -Maxswap "TEST_VALUE" -Disk "TEST_VALUE" -Diskwrite "TEST_VALUE" -Uptime "TEST_VALUE" -Netin "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesLxcStatusCurrent
            #$NewObject.property | Should -Be 0
        }
    }
}
