#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesSyslogInner' {
    Context 'PVENodesSyslogInner' {
        It 'Initialize-PVENodesSyslogInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesSyslogInner -T "TEST_VALUE" -N "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesSyslogInner
            #$NewObject.property | Should -Be 0
        }
    }
}
