#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesLxcMtunnelwebsocket' {
    Context 'PVENodesLxcMtunnelwebsocket' {
        It 'Initialize-PVENodesLxcMtunnelwebsocket' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesLxcMtunnelwebsocket -Port "TEST_VALUE" -Socket "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesLxcMtunnelwebsocket
            #$NewObject.property | Should -Be 0
        }
    }
}
