#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesHardwarePciAVInner' {
    Context 'PVENodesHardwarePciAVInner' {
        It 'Initialize-PVENodesHardwarePciAVInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesHardwarePciAVInner -Method "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesHardwarePciAVInner
            #$NewObject.property | Should -Be 0
        }
    }
}
