#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesQemuStatusCurrent' {
    Context 'PVENodesQemuStatusCurrent' {
        It 'Initialize-PVENodesQemuStatusCurrent' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesQemuStatusCurrent -Maxdisk "TEST_VALUE" -RunningMachine "TEST_VALUE" -Diskread "TEST_VALUE" -Ha "TEST_VALUE" -Netout "TEST_VALUE" -Spice "TEST_VALUE" -Status "TEST_VALUE" -Cpus "TEST_VALUE" -Vmid "TEST_VALUE" -Maxmem "TEST_VALUE" -Qmpstatus "TEST_VALUE" -Clipboard "TEST_VALUE" -RunningQemu "TEST_VALUE" -Agent "TEST_VALUE" -Lock "TEST_VALUE" -Name "TEST_VALUE" -VarPid "TEST_VALUE" -Template "TEST_VALUE" -Tags "TEST_VALUE" -Diskwrite "TEST_VALUE" -Uptime "TEST_VALUE" -Netin "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesQemuStatusCurrent
            #$NewObject.property | Should -Be 0
        }
    }
}
