#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesDisksLvmthinInner' {
    Context 'PVENodesDisksLvmthinInner' {
        It 'Initialize-PVENodesDisksLvmthinInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesDisksLvmthinInner -Used "TEST_VALUE" -Lv "TEST_VALUE" -MetadataUsed "TEST_VALUE" -MetadataSize "TEST_VALUE" -Vg "TEST_VALUE" -LvSize "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesDisksLvmthinInner
            #$NewObject.property | Should -Be 0
        }
    }
}
