#
# Proxmox VE Module 1.0
# Generated OpenApiDescription to render Modules via OpenapiGenerator
# Version: 0.1
# Contact: 
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ProxmoxPVE' -name 'PVENodesHardwarePciInner' {
    Context 'PVENodesHardwarePciInner' {
        It 'Initialize-PVENodesHardwarePciInner' {
            # a simple test to create an object
            #$NewObject = Initialize-PVENodesHardwarePciInner -Iommugroup "TEST_VALUE" -SubsystemVendorName "TEST_VALUE" -SubsystemDeviceName "TEST_VALUE" -Device "TEST_VALUE" -SubsystemDevice "TEST_VALUE" -Vendor "TEST_VALUE" -Id "TEST_VALUE" -Class "TEST_VALUE" -SubsystemVendor "TEST_VALUE" -VendorName "TEST_VALUE" -Mdev "TEST_VALUE" -DeviceName "TEST_VALUE"
            #$NewObject | Should -BeOfType NodesHardwarePciInner
            #$NewObject.property | Should -Be 0
        }
    }
}
